### ISSUE TITLE
你好，我已经成功部署到本地了，但是执行spider163 --help老是提示如下错了，配置文件改了很多次也一样，

### ISSUE THREAD

**Issue by 985211yygg** [chengyumeng/spider163#10]
C:\WINDOWS\system32>spider163 --help
Traceback (most recent call last):
  File "H:\python\Python27\Scripts\spider163-script.py", line 11, in <module>
    load_entry_point('spider163==2.5.4', 'console_scripts', 'spider163')()
  File "h:\python\python27\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "h:\python\python27\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "h:\python\python27\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "h:\python\python27\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "h:\python\python27\lib\site-packages\spider163\bin\cli.py", line 9, in <module>
    from spider163.utils import pysql
  File "h:\python\python27\lib\site-packages\spider163\utils\pysql.py", line 10, in <module>
    from spider163 import settings
  File "h:\python\python27\lib\site-packages\spider163\settings.py", line 5, in <module>
    from spider163.utils import config
  File "h:\python\python27\lib\site-packages\spider163\utils\config.py", line 11, in <module>
    PATH = os.environ.get("HOME") + "/spider163"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

》》》》》 spider163.conf
[core]
db=mysql://root:985211yyg@localhost/Local?charset=utf8mb4
port=3306

》》》》》SPIDER163_PATH
H:\python\workspace\song163

**Comment by RominYue** [comment]
我的几点猜想， os.environ.get("HOME") + "/spider163"出错

1. windows是不是没有‘HOME’这个环境变量，可能需要自己创建
2. windows下分隔符是'\', 不是 ‘/’

**Comment by Chengyumeng** [comment]
windows下路径分隔符为\,实际字符串可能需要\\转义一下的形式，建议试试。本项目在windows下没有进行过测试。

**Comment by palysoysauce** [comment]
在Windows的确有很多报错。。。
还是用Linux吧。
