### ISSUE TITLE
pip install failed on termux(Android)

### ISSUE THREAD

**Issue by yangrq** [Chengyumeng/spider163#14]
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/tmp/pip-build-mmjqcjfd/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/data/data/com.termux/files/usr/tmp/pip-build-mmjqcjfd/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-build-mmjqcjfd/MySQL-python/
```

**Comment by yangrq** [comment]
It seems that the failure was caused by MySQL-Python,so maybe I shouldn't open a issue here. :)

**Comment by Chengyumeng** [comment]
需要安装python mysql扩展，你可以本地装一下（貌似需要安装mysql的库）

**Comment by Chengyumeng** [comment]
https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser

**Comment by Chengyumeng** [comment]
本项目一般在python2下测试运行

**Comment by yangrq** [comment]
I find that MySQL can't be installed on termux, and I USED PYTHON2 TO RUN THE SCRIPT.So the issue could be closed now, thanks a lot!
Another suggestion: add sqlite supports.
